using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqGoods.DomainLogic.Tables;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqGoods.DomainLogic.Models
{
    public record SgAttributeItem
    {
        //Auto-generated by SqExpress Code-gen util
        public SgAttributeItem(Guid attributeSetId, Guid attributeId, string name, int order)
        {
            this.AttributeSetId = attributeSetId;
            this.AttributeId = attributeId;
            this.Name = name;
            this.Order = order;
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttributeItem Read(ISqDataRecordReader record, TblAttributeSet table)
        {
            return new SgAttributeItem(attributeSetId: table.AttributeSetId.Read(record), attributeId: table.AttributeId.Read(record), name: table.Name.Read(record), order: table.Order.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttributeItem ReadWithPrefix(ISqDataRecordReader record, TblAttributeSet table, string prefix)
        {
            return new SgAttributeItem(attributeSetId: table.AttributeSetId.Read(record, prefix + table.AttributeSetId.ColumnName.Name), attributeId: table.AttributeId.Read(record, prefix + table.AttributeId.ColumnName.Name), name: table.Name.Read(record, prefix + table.Name.ColumnName.Name), order: table.Order.Read(record, prefix + table.Order.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttributeItem ReadOrdinal(ISqDataRecordReader record, TblAttributeSet table, int offset)
        {
            return new SgAttributeItem(attributeSetId: table.AttributeSetId.Read(record, offset), attributeId: table.AttributeId.Read(record, offset + 1), name: table.Name.Read(record, offset + 2), order: table.Order.Read(record, offset + 3));
        }

        //Auto-generated by SqExpress Code-gen util
        public Guid AttributeSetId { get; }

        //Auto-generated by SqExpress Code-gen util
        public Guid AttributeId { get; }

        //Auto-generated by SqExpress Code-gen util
        public string Name { get; }

        //Auto-generated by SqExpress Code-gen util
        public int Order { get; }

        //Auto-generated by SqExpress Code-gen util
        public static TableColumn[] GetColumns(TblAttributeSet table)
        {
            return new TableColumn[]{table.AttributeSetId, table.AttributeId, table.Name, table.Order};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(TblAttributeSet table, string prefix)
        {
            return new ExprAliasedColumn[]{table.AttributeSetId.As(prefix + table.AttributeSetId.ColumnName.Name), table.AttributeId.As(prefix + table.AttributeId.ColumnName.Name), table.Name.As(prefix + table.Name.ColumnName.Name), table.Order.As(prefix + table.Order.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, TblAttributeSet table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, TblAttributeSet table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetMapping(IDataMapSetter<TblAttributeSet, SgAttributeItem> s)
        {
            return s.Set(s.Target.AttributeSetId, s.Source.AttributeSetId).Set(s.Target.AttributeId, s.Source.AttributeId).Set(s.Target.Name, s.Source.Name).Set(s.Target.Order, s.Source.Order);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateKeyMapping(IDataMapSetter<TblAttributeSet, SgAttributeItem> s)
        {
            return s.Set(s.Target.AttributeSetId, s.Source.AttributeSetId);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateMapping(IDataMapSetter<TblAttributeSet, SgAttributeItem> s)
        {
            return s.Set(s.Target.AttributeId, s.Source.AttributeId).Set(s.Target.Name, s.Source.Name).Set(s.Target.Order, s.Source.Order);
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<SgAttributeItem, TblAttributeSet> GetReader()
        {
            return SgAttributeItemReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgAttributeItemReader : ISqModelReader<SgAttributeItem, TblAttributeSet>
        {
            public static SgAttributeItemReader Instance { get; } = new SgAttributeItemReader();
            IReadOnlyList<ExprColumn> ISqModelReader<SgAttributeItem, TblAttributeSet>.GetColumns(TblAttributeSet table)
            {
                return SgAttributeItem.GetColumns(table);
            }

            SgAttributeItem ISqModelReader<SgAttributeItem, TblAttributeSet>.Read(ISqDataRecordReader record, TblAttributeSet table)
            {
                return SgAttributeItem.Read(record, table);
            }

            SgAttributeItem ISqModelReader<SgAttributeItem, TblAttributeSet>.ReadOrdinal(ISqDataRecordReader record, TblAttributeSet table, int offset)
            {
                return SgAttributeItem.ReadOrdinal(record, table, offset);
            }
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelUpdaterKey<SgAttributeItem, TblAttributeSet> GetUpdater()
        {
            return SgAttributeItemUpdater.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgAttributeItemUpdater : ISqModelUpdaterKey<SgAttributeItem, TblAttributeSet>
        {
            public static SgAttributeItemUpdater Instance { get; } = new SgAttributeItemUpdater();
            IRecordSetterNext ISqModelUpdater<SgAttributeItem, TblAttributeSet>.GetMapping(IDataMapSetter<TblAttributeSet, SgAttributeItem> dataMapSetter)
            {
                return SgAttributeItem.GetMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<SgAttributeItem, TblAttributeSet>.GetUpdateKeyMapping(IDataMapSetter<TblAttributeSet, SgAttributeItem> dataMapSetter)
            {
                return SgAttributeItem.GetUpdateKeyMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<SgAttributeItem, TblAttributeSet>.GetUpdateMapping(IDataMapSetter<TblAttributeSet, SgAttributeItem> dataMapSetter)
            {
                return SgAttributeItem.GetUpdateMapping(dataMapSetter);
            }
        }
    }
}