using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqGoods.DomainLogic.Tables;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqGoods.DomainLogic.Models
{
    public record SgAttributeSetId
    {
        //Auto-generated by SqExpress Code-gen util
        public SgAttributeSetId(Guid attributeSetId, Guid attributeId)
        {
            this.AttributeSetId = attributeSetId;
            this.AttributeId = attributeId;
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttributeSetId Read(ISqDataRecordReader record, TblAttributeSet table)
        {
            return new SgAttributeSetId(attributeSetId: table.AttributeSetId.Read(record), attributeId: table.AttributeId.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttributeSetId ReadWithPrefix(ISqDataRecordReader record, TblAttributeSet table, string prefix)
        {
            return new SgAttributeSetId(attributeSetId: table.AttributeSetId.Read(record, prefix + table.AttributeSetId.ColumnName.Name), attributeId: table.AttributeId.Read(record, prefix + table.AttributeId.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttributeSetId ReadOrdinal(ISqDataRecordReader record, TblAttributeSet table, int offset)
        {
            return new SgAttributeSetId(attributeSetId: table.AttributeSetId.Read(record, offset), attributeId: table.AttributeId.Read(record, offset + 1));
        }

        //Auto-generated by SqExpress Code-gen util
        public Guid AttributeSetId { get; }

        //Auto-generated by SqExpress Code-gen util
        public Guid AttributeId { get; }

        //Auto-generated by SqExpress Code-gen util
        public static TableColumn[] GetColumns(TblAttributeSet table)
        {
            return new TableColumn[]{table.AttributeSetId, table.AttributeId};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(TblAttributeSet table, string prefix)
        {
            return new ExprAliasedColumn[]{table.AttributeSetId.As(prefix + table.AttributeSetId.ColumnName.Name), table.AttributeId.As(prefix + table.AttributeId.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, TblAttributeSet table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, TblAttributeSet table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetMapping(IDataMapSetter<TblAttributeSet, SgAttributeSetId> s)
        {
            return s.Set(s.Target.AttributeSetId, s.Source.AttributeSetId).Set(s.Target.AttributeId, s.Source.AttributeId);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateKeyMapping(IDataMapSetter<TblAttributeSet, SgAttributeSetId> s)
        {
            return s.Set(s.Target.AttributeSetId, s.Source.AttributeSetId);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateMapping(IDataMapSetter<TblAttributeSet, SgAttributeSetId> s)
        {
            return s.Set(s.Target.AttributeId, s.Source.AttributeId);
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<SgAttributeSetId, TblAttributeSet> GetReader()
        {
            return SgAttributeSetIdReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgAttributeSetIdReader : ISqModelReader<SgAttributeSetId, TblAttributeSet>
        {
            public static SgAttributeSetIdReader Instance { get; } = new SgAttributeSetIdReader();
            IReadOnlyList<ExprColumn> ISqModelReader<SgAttributeSetId, TblAttributeSet>.GetColumns(TblAttributeSet table)
            {
                return SgAttributeSetId.GetColumns(table);
            }

            SgAttributeSetId ISqModelReader<SgAttributeSetId, TblAttributeSet>.Read(ISqDataRecordReader record, TblAttributeSet table)
            {
                return SgAttributeSetId.Read(record, table);
            }

            SgAttributeSetId ISqModelReader<SgAttributeSetId, TblAttributeSet>.ReadOrdinal(ISqDataRecordReader record, TblAttributeSet table, int offset)
            {
                return SgAttributeSetId.ReadOrdinal(record, table, offset);
            }
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelUpdaterKey<SgAttributeSetId, TblAttributeSet> GetUpdater()
        {
            return SgAttributeSetIdUpdater.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgAttributeSetIdUpdater : ISqModelUpdaterKey<SgAttributeSetId, TblAttributeSet>
        {
            public static SgAttributeSetIdUpdater Instance { get; } = new SgAttributeSetIdUpdater();
            IRecordSetterNext ISqModelUpdater<SgAttributeSetId, TblAttributeSet>.GetMapping(IDataMapSetter<TblAttributeSet, SgAttributeSetId> dataMapSetter)
            {
                return SgAttributeSetId.GetMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<SgAttributeSetId, TblAttributeSet>.GetUpdateKeyMapping(IDataMapSetter<TblAttributeSet, SgAttributeSetId> dataMapSetter)
            {
                return SgAttributeSetId.GetUpdateKeyMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<SgAttributeSetId, TblAttributeSet>.GetUpdateMapping(IDataMapSetter<TblAttributeSet, SgAttributeSetId> dataMapSetter)
            {
                return SgAttributeSetId.GetUpdateMapping(dataMapSetter);
            }
        }
    }
}