using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqGoods.DomainLogic.Views;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqGoods.DomainLogic.Models
{
    public record SgAttributeSetItemsNum
    {
        //Auto-generated by SqExpress Code-gen util
        public SgAttributeSetItemsNum(Guid attributeId, int setItemsNum)
        {
            this.AttributeId = attributeId;
            this.SetItemsNum = setItemsNum;
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttributeSetItemsNum Read(ISqDataRecordReader record, VwAttributeSetItemsNum table)
        {
            return new SgAttributeSetItemsNum(attributeId: table.AttributeId.Read(record), setItemsNum: table.SetItemsNum.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttributeSetItemsNum ReadWithPrefix(ISqDataRecordReader record, VwAttributeSetItemsNum table, string prefix)
        {
            return new SgAttributeSetItemsNum(attributeId: table.AttributeId.Read(record, prefix + table.AttributeId.ColumnName.Name), setItemsNum: table.SetItemsNum.Read(record, prefix + table.SetItemsNum.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttributeSetItemsNum ReadOrdinal(ISqDataRecordReader record, VwAttributeSetItemsNum table, int offset)
        {
            return new SgAttributeSetItemsNum(attributeId: table.AttributeId.Read(record, offset), setItemsNum: table.SetItemsNum.Read(record, offset + 1));
        }

        //Auto-generated by SqExpress Code-gen util
        public Guid AttributeId { get; }

        //Auto-generated by SqExpress Code-gen util
        public int SetItemsNum { get; }

        //Auto-generated by SqExpress Code-gen util
        public static ExprColumn[] GetColumns(VwAttributeSetItemsNum table)
        {
            return new ExprColumn[]{table.AttributeId, table.SetItemsNum};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(VwAttributeSetItemsNum table, string prefix)
        {
            return new ExprAliasedColumn[]{table.AttributeId.As(prefix + table.AttributeId.ColumnName.Name), table.SetItemsNum.As(prefix + table.SetItemsNum.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, VwAttributeSetItemsNum table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, VwAttributeSetItemsNum table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<SgAttributeSetItemsNum, VwAttributeSetItemsNum> GetReader()
        {
            return SgAttributeSetItemsNumReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgAttributeSetItemsNumReader : ISqModelReader<SgAttributeSetItemsNum, VwAttributeSetItemsNum>
        {
            public static SgAttributeSetItemsNumReader Instance { get; } = new SgAttributeSetItemsNumReader();
            IReadOnlyList<ExprColumn> ISqModelReader<SgAttributeSetItemsNum, VwAttributeSetItemsNum>.GetColumns(VwAttributeSetItemsNum table)
            {
                return SgAttributeSetItemsNum.GetColumns(table);
            }

            SgAttributeSetItemsNum ISqModelReader<SgAttributeSetItemsNum, VwAttributeSetItemsNum>.Read(ISqDataRecordReader record, VwAttributeSetItemsNum table)
            {
                return SgAttributeSetItemsNum.Read(record, table);
            }

            SgAttributeSetItemsNum ISqModelReader<SgAttributeSetItemsNum, VwAttributeSetItemsNum>.ReadOrdinal(ISqDataRecordReader record, VwAttributeSetItemsNum table, int offset)
            {
                return SgAttributeSetItemsNum.ReadOrdinal(record, table, offset);
            }
        }
    }
}