using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqGoods.DomainLogic.Tables;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqGoods.DomainLogic.Models
{
    public record SgAttribute
    {
        //Auto-generated by SqExpress Code-gen util
        public SgAttribute(Guid id, string name, SgAttributeType type, string? unit)
        {
            this.Id = id;
            this.Name = name;
            this.Type = type;
            this.Unit = unit;
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttribute Read(ISqDataRecordReader record, TblAttribute table)
        {
            return new SgAttribute(id: table.AttributeId.Read(record), name: table.Name.Read(record), type: (SgAttributeType)table.Type.Read(record), unit: table.Unit.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttribute ReadWithPrefix(ISqDataRecordReader record, TblAttribute table, string prefix)
        {
            return new SgAttribute(id: table.AttributeId.Read(record, prefix + table.AttributeId.ColumnName.Name), name: table.Name.Read(record, prefix + table.Name.ColumnName.Name), type: (SgAttributeType)table.Type.Read(record, prefix + table.Type.ColumnName.Name), unit: table.Unit.Read(record, prefix + table.Unit.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttribute ReadOrdinal(ISqDataRecordReader record, TblAttribute table, int offset)
        {
            return new SgAttribute(id: table.AttributeId.Read(record, offset), name: table.Name.Read(record, offset + 1), type: (SgAttributeType)table.Type.Read(record, offset + 2), unit: table.Unit.Read(record, offset + 3));
        }

        //Auto-generated by SqExpress Code-gen util
        public Guid Id { get; }

        //Auto-generated by SqExpress Code-gen util
        public string Name { get; }

        //Auto-generated by SqExpress Code-gen util
        public SgAttributeType Type { get; }

        //Auto-generated by SqExpress Code-gen util
        public string? Unit { get; }

        //Auto-generated by SqExpress Code-gen util
        public static TableColumn[] GetColumns(TblAttribute table)
        {
            return new TableColumn[]{table.AttributeId, table.Name, table.Type, table.Unit};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(TblAttribute table, string prefix)
        {
            return new ExprAliasedColumn[]{table.AttributeId.As(prefix + table.AttributeId.ColumnName.Name), table.Name.As(prefix + table.Name.ColumnName.Name), table.Type.As(prefix + table.Type.ColumnName.Name), table.Unit.As(prefix + table.Unit.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, TblAttribute table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, TblAttribute table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetMapping(IDataMapSetter<TblAttribute, SgAttribute> s)
        {
            return s.Set(s.Target.AttributeId, s.Source.Id).Set(s.Target.Name, s.Source.Name).Set(s.Target.Type, (short)s.Source.Type).Set(s.Target.Unit, s.Source.Unit);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateKeyMapping(IDataMapSetter<TblAttribute, SgAttribute> s)
        {
            return s.Set(s.Target.AttributeId, s.Source.Id);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateMapping(IDataMapSetter<TblAttribute, SgAttribute> s)
        {
            return s.Set(s.Target.Name, s.Source.Name).Set(s.Target.Type, (short)s.Source.Type).Set(s.Target.Unit, s.Source.Unit);
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<SgAttribute, TblAttribute> GetReader()
        {
            return SgAttributeReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgAttributeReader : ISqModelReader<SgAttribute, TblAttribute>
        {
            public static SgAttributeReader Instance { get; } = new SgAttributeReader();
            IReadOnlyList<ExprColumn> ISqModelReader<SgAttribute, TblAttribute>.GetColumns(TblAttribute table)
            {
                return SgAttribute.GetColumns(table);
            }

            SgAttribute ISqModelReader<SgAttribute, TblAttribute>.Read(ISqDataRecordReader record, TblAttribute table)
            {
                return SgAttribute.Read(record, table);
            }

            SgAttribute ISqModelReader<SgAttribute, TblAttribute>.ReadOrdinal(ISqDataRecordReader record, TblAttribute table, int offset)
            {
                return SgAttribute.ReadOrdinal(record, table, offset);
            }
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelUpdaterKey<SgAttribute, TblAttribute> GetUpdater()
        {
            return SgAttributeUpdater.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgAttributeUpdater : ISqModelUpdaterKey<SgAttribute, TblAttribute>
        {
            public static SgAttributeUpdater Instance { get; } = new SgAttributeUpdater();
            IRecordSetterNext ISqModelUpdater<SgAttribute, TblAttribute>.GetMapping(IDataMapSetter<TblAttribute, SgAttribute> dataMapSetter)
            {
                return SgAttribute.GetMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<SgAttribute, TblAttribute>.GetUpdateKeyMapping(IDataMapSetter<TblAttribute, SgAttribute> dataMapSetter)
            {
                return SgAttribute.GetUpdateKeyMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<SgAttribute, TblAttribute>.GetUpdateMapping(IDataMapSetter<TblAttribute, SgAttribute> dataMapSetter)
            {
                return SgAttribute.GetUpdateMapping(dataMapSetter);
            }
        }
    }
}