using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqGoods.DomainLogic.Tables;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqGoods.DomainLogic.Models
{
    public record SgAttributeItemName
    {
        //Auto-generated by SqExpress Code-gen util
        public SgAttributeItemName(Guid attributeSetId, string name)
        {
            this.AttributeSetId = attributeSetId;
            this.Name = name;
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttributeItemName Read(ISqDataRecordReader record, TblAttributeSet table)
        {
            return new SgAttributeItemName(attributeSetId: table.AttributeSetId.Read(record), name: table.Name.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttributeItemName ReadWithPrefix(ISqDataRecordReader record, TblAttributeSet table, string prefix)
        {
            return new SgAttributeItemName(attributeSetId: table.AttributeSetId.Read(record, prefix + table.AttributeSetId.ColumnName.Name), name: table.Name.Read(record, prefix + table.Name.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttributeItemName ReadOrdinal(ISqDataRecordReader record, TblAttributeSet table, int offset)
        {
            return new SgAttributeItemName(attributeSetId: table.AttributeSetId.Read(record, offset), name: table.Name.Read(record, offset + 1));
        }

        //Auto-generated by SqExpress Code-gen util
        public Guid AttributeSetId { get; }

        //Auto-generated by SqExpress Code-gen util
        public string Name { get; }

        //Auto-generated by SqExpress Code-gen util
        public static TableColumn[] GetColumns(TblAttributeSet table)
        {
            return new TableColumn[]{table.AttributeSetId, table.Name};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(TblAttributeSet table, string prefix)
        {
            return new ExprAliasedColumn[]{table.AttributeSetId.As(prefix + table.AttributeSetId.ColumnName.Name), table.Name.As(prefix + table.Name.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, TblAttributeSet table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, TblAttributeSet table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetMapping(IDataMapSetter<TblAttributeSet, SgAttributeItemName> s)
        {
            return s.Set(s.Target.AttributeSetId, s.Source.AttributeSetId).Set(s.Target.Name, s.Source.Name);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateKeyMapping(IDataMapSetter<TblAttributeSet, SgAttributeItemName> s)
        {
            return s.Set(s.Target.AttributeSetId, s.Source.AttributeSetId);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateMapping(IDataMapSetter<TblAttributeSet, SgAttributeItemName> s)
        {
            return s.Set(s.Target.Name, s.Source.Name);
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<SgAttributeItemName, TblAttributeSet> GetReader()
        {
            return SgAttributeItemNameReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgAttributeItemNameReader : ISqModelReader<SgAttributeItemName, TblAttributeSet>
        {
            public static SgAttributeItemNameReader Instance { get; } = new SgAttributeItemNameReader();
            IReadOnlyList<ExprColumn> ISqModelReader<SgAttributeItemName, TblAttributeSet>.GetColumns(TblAttributeSet table)
            {
                return SgAttributeItemName.GetColumns(table);
            }

            SgAttributeItemName ISqModelReader<SgAttributeItemName, TblAttributeSet>.Read(ISqDataRecordReader record, TblAttributeSet table)
            {
                return SgAttributeItemName.Read(record, table);
            }

            SgAttributeItemName ISqModelReader<SgAttributeItemName, TblAttributeSet>.ReadOrdinal(ISqDataRecordReader record, TblAttributeSet table, int offset)
            {
                return SgAttributeItemName.ReadOrdinal(record, table, offset);
            }
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelUpdaterKey<SgAttributeItemName, TblAttributeSet> GetUpdater()
        {
            return SgAttributeItemNameUpdater.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgAttributeItemNameUpdater : ISqModelUpdaterKey<SgAttributeItemName, TblAttributeSet>
        {
            public static SgAttributeItemNameUpdater Instance { get; } = new SgAttributeItemNameUpdater();
            IRecordSetterNext ISqModelUpdater<SgAttributeItemName, TblAttributeSet>.GetMapping(IDataMapSetter<TblAttributeSet, SgAttributeItemName> dataMapSetter)
            {
                return SgAttributeItemName.GetMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<SgAttributeItemName, TblAttributeSet>.GetUpdateKeyMapping(IDataMapSetter<TblAttributeSet, SgAttributeItemName> dataMapSetter)
            {
                return SgAttributeItemName.GetUpdateKeyMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<SgAttributeItemName, TblAttributeSet>.GetUpdateMapping(IDataMapSetter<TblAttributeSet, SgAttributeItemName> dataMapSetter)
            {
                return SgAttributeItemName.GetUpdateMapping(dataMapSetter);
            }
        }

        public Guid AttributeId { get; }
    }
}