using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqGoods.DomainLogic.Tables;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqGoods.DomainLogic.Models
{
    public record SgAttributeTypeId
    {
        //Auto-generated by SqExpress Code-gen util
        public SgAttributeTypeId(Guid id, SgAttributeType type)
        {
            this.Id = id;
            this.Type = type;
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttributeTypeId Read(ISqDataRecordReader record, TblAttribute table)
        {
            return new SgAttributeTypeId(id: table.AttributeId.Read(record), type: (SgAttributeType)table.Type.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttributeTypeId ReadWithPrefix(ISqDataRecordReader record, TblAttribute table, string prefix)
        {
            return new SgAttributeTypeId(id: table.AttributeId.Read(record, prefix + table.AttributeId.ColumnName.Name), type: (SgAttributeType)table.Type.Read(record, prefix + table.Type.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttributeTypeId ReadOrdinal(ISqDataRecordReader record, TblAttribute table, int offset)
        {
            return new SgAttributeTypeId(id: table.AttributeId.Read(record, offset), type: (SgAttributeType)table.Type.Read(record, offset + 1));
        }

        //Auto-generated by SqExpress Code-gen util
        public Guid Id { get; }

        //Auto-generated by SqExpress Code-gen util
        public SgAttributeType Type { get; }

        //Auto-generated by SqExpress Code-gen util
        public static TableColumn[] GetColumns(TblAttribute table)
        {
            return new TableColumn[]{table.AttributeId, table.Type};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(TblAttribute table, string prefix)
        {
            return new ExprAliasedColumn[]{table.AttributeId.As(prefix + table.AttributeId.ColumnName.Name), table.Type.As(prefix + table.Type.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, TblAttribute table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, TblAttribute table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetMapping(IDataMapSetter<TblAttribute, SgAttributeTypeId> s)
        {
            return s.Set(s.Target.AttributeId, s.Source.Id).Set(s.Target.Type, (short)s.Source.Type);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateKeyMapping(IDataMapSetter<TblAttribute, SgAttributeTypeId> s)
        {
            return s.Set(s.Target.AttributeId, s.Source.Id);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateMapping(IDataMapSetter<TblAttribute, SgAttributeTypeId> s)
        {
            return s.Set(s.Target.Type, (short)s.Source.Type);
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<SgAttributeTypeId, TblAttribute> GetReader()
        {
            return SgAttributeTypeIdReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgAttributeTypeIdReader : ISqModelReader<SgAttributeTypeId, TblAttribute>
        {
            public static SgAttributeTypeIdReader Instance { get; } = new SgAttributeTypeIdReader();
            IReadOnlyList<ExprColumn> ISqModelReader<SgAttributeTypeId, TblAttribute>.GetColumns(TblAttribute table)
            {
                return SgAttributeTypeId.GetColumns(table);
            }

            SgAttributeTypeId ISqModelReader<SgAttributeTypeId, TblAttribute>.Read(ISqDataRecordReader record, TblAttribute table)
            {
                return SgAttributeTypeId.Read(record, table);
            }

            SgAttributeTypeId ISqModelReader<SgAttributeTypeId, TblAttribute>.ReadOrdinal(ISqDataRecordReader record, TblAttribute table, int offset)
            {
                return SgAttributeTypeId.ReadOrdinal(record, table, offset);
            }
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelUpdaterKey<SgAttributeTypeId, TblAttribute> GetUpdater()
        {
            return SgAttributeTypeIdUpdater.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgAttributeTypeIdUpdater : ISqModelUpdaterKey<SgAttributeTypeId, TblAttribute>
        {
            public static SgAttributeTypeIdUpdater Instance { get; } = new SgAttributeTypeIdUpdater();
            IRecordSetterNext ISqModelUpdater<SgAttributeTypeId, TblAttribute>.GetMapping(IDataMapSetter<TblAttribute, SgAttributeTypeId> dataMapSetter)
            {
                return SgAttributeTypeId.GetMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<SgAttributeTypeId, TblAttribute>.GetUpdateKeyMapping(IDataMapSetter<TblAttribute, SgAttributeTypeId> dataMapSetter)
            {
                return SgAttributeTypeId.GetUpdateKeyMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<SgAttributeTypeId, TblAttribute>.GetUpdateMapping(IDataMapSetter<TblAttribute, SgAttributeTypeId> dataMapSetter)
            {
                return SgAttributeTypeId.GetUpdateMapping(dataMapSetter);
            }
        }

        private class SgAttributeNameAndTypeReader : ISqModelReader<SgAttributeTypeId, TblAttribute>
        {
            public static SgAttributeNameAndTypeReader Instance { get; } = new SgAttributeNameAndTypeReader();
            IReadOnlyList<ExprColumn> ISqModelReader<SgAttributeTypeId, TblAttribute>.GetColumns(TblAttribute table)
            {
                return SgAttributeTypeId.GetColumns(table);
            }

            SgAttributeTypeId ISqModelReader<SgAttributeTypeId, TblAttribute>.Read(ISqDataRecordReader record, TblAttribute table)
            {
                return SgAttributeTypeId.Read(record, table);
            }

            SgAttributeTypeId ISqModelReader<SgAttributeTypeId, TblAttribute>.ReadOrdinal(ISqDataRecordReader record, TblAttribute table, int offset)
            {
                return SgAttributeTypeId.ReadOrdinal(record, table, offset);
            }
        }

        private class SgAttributeNameAndTypeUpdater : ISqModelUpdaterKey<SgAttributeTypeId, TblAttribute>
        {
            public static SgAttributeNameAndTypeUpdater Instance { get; } = new SgAttributeNameAndTypeUpdater();
            IRecordSetterNext ISqModelUpdater<SgAttributeTypeId, TblAttribute>.GetMapping(IDataMapSetter<TblAttribute, SgAttributeTypeId> dataMapSetter)
            {
                return SgAttributeTypeId.GetMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<SgAttributeTypeId, TblAttribute>.GetUpdateKeyMapping(IDataMapSetter<TblAttribute, SgAttributeTypeId> dataMapSetter)
            {
                return SgAttributeTypeId.GetUpdateKeyMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<SgAttributeTypeId, TblAttribute>.GetUpdateMapping(IDataMapSetter<TblAttribute, SgAttributeTypeId> dataMapSetter)
            {
                return SgAttributeTypeId.GetUpdateMapping(dataMapSetter);
            }
        }
    }
}