using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqGoods.DomainLogic.Tables;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqGoods.DomainLogic.Models
{
    public record SgAttributeId
    {
        //Auto-generated by SqExpress Code-gen util
        public SgAttributeId(Guid id)
        {
            this.Id = id;
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttributeId Read(ISqDataRecordReader record, TblAttribute table)
        {
            return new SgAttributeId(id: table.AttributeId.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttributeId ReadWithPrefix(ISqDataRecordReader record, TblAttribute table, string prefix)
        {
            return new SgAttributeId(id: table.AttributeId.Read(record, prefix + table.AttributeId.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgAttributeId ReadOrdinal(ISqDataRecordReader record, TblAttribute table, int offset)
        {
            return new SgAttributeId(id: table.AttributeId.Read(record, offset));
        }

        //Auto-generated by SqExpress Code-gen util
        public Guid Id { get; }

        //Auto-generated by SqExpress Code-gen util
        public static TableColumn[] GetColumns(TblAttribute table)
        {
            return new TableColumn[]{table.AttributeId};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(TblAttribute table, string prefix)
        {
            return new ExprAliasedColumn[]{table.AttributeId.As(prefix + table.AttributeId.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, TblAttribute table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, TblAttribute table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetMapping(IDataMapSetter<TblAttribute, SgAttributeId> s)
        {
            return s.Set(s.Target.AttributeId, s.Source.Id);
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<SgAttributeId, TblAttribute> GetReader()
        {
            return SgAttributeIdReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgAttributeIdReader : ISqModelReader<SgAttributeId, TblAttribute>
        {
            public static SgAttributeIdReader Instance { get; } = new SgAttributeIdReader();
            IReadOnlyList<ExprColumn> ISqModelReader<SgAttributeId, TblAttribute>.GetColumns(TblAttribute table)
            {
                return SgAttributeId.GetColumns(table);
            }

            SgAttributeId ISqModelReader<SgAttributeId, TblAttribute>.Read(ISqDataRecordReader record, TblAttribute table)
            {
                return SgAttributeId.Read(record, table);
            }

            SgAttributeId ISqModelReader<SgAttributeId, TblAttribute>.ReadOrdinal(ISqDataRecordReader record, TblAttribute table, int offset)
            {
                return SgAttributeId.ReadOrdinal(record, table, offset);
            }
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelUpdater<SgAttributeId, TblAttribute> GetUpdater()
        {
            return SgAttributeIdUpdater.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgAttributeIdUpdater : ISqModelUpdater<SgAttributeId, TblAttribute>
        {
            public static SgAttributeIdUpdater Instance { get; } = new SgAttributeIdUpdater();
            IRecordSetterNext ISqModelUpdater<SgAttributeId, TblAttribute>.GetMapping(IDataMapSetter<TblAttribute, SgAttributeId> dataMapSetter)
            {
                return SgAttributeId.GetMapping(dataMapSetter);
            }
        }
    }
}