using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqGoods.DomainLogic.Tables;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqGoods.DomainLogic.Models
{
    public record SgCategoryAttributeOrder
    {
        //Auto-generated by SqExpress Code-gen util
        public SgCategoryAttributeOrder(Guid categoryId, Guid attributeId, int order)
        {
            this.CategoryId = categoryId;
            this.AttributeId = attributeId;
            this.Order = order;
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgCategoryAttributeOrder Read(ISqDataRecordReader record, TblCategoryAttribute table)
        {
            return new SgCategoryAttributeOrder(categoryId: table.CategoryId.Read(record), attributeId: table.AttributeId.Read(record), order: table.Order.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgCategoryAttributeOrder ReadWithPrefix(ISqDataRecordReader record, TblCategoryAttribute table, string prefix)
        {
            return new SgCategoryAttributeOrder(categoryId: table.CategoryId.Read(record, prefix + table.CategoryId.ColumnName.Name), attributeId: table.AttributeId.Read(record, prefix + table.AttributeId.ColumnName.Name), order: table.Order.Read(record, prefix + table.Order.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgCategoryAttributeOrder ReadOrdinal(ISqDataRecordReader record, TblCategoryAttribute table, int offset)
        {
            return new SgCategoryAttributeOrder(categoryId: table.CategoryId.Read(record, offset), attributeId: table.AttributeId.Read(record, offset + 1), order: table.Order.Read(record, offset + 2));
        }

        //Auto-generated by SqExpress Code-gen util
        public Guid CategoryId { get; }

        //Auto-generated by SqExpress Code-gen util
        public Guid AttributeId { get; }

        //Auto-generated by SqExpress Code-gen util
        public int Order { get; }

        //Auto-generated by SqExpress Code-gen util
        public static TableColumn[] GetColumns(TblCategoryAttribute table)
        {
            return new TableColumn[]{table.CategoryId, table.AttributeId, table.Order};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(TblCategoryAttribute table, string prefix)
        {
            return new ExprAliasedColumn[]{table.CategoryId.As(prefix + table.CategoryId.ColumnName.Name), table.AttributeId.As(prefix + table.AttributeId.ColumnName.Name), table.Order.As(prefix + table.Order.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, TblCategoryAttribute table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, TblCategoryAttribute table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetMapping(IDataMapSetter<TblCategoryAttribute, SgCategoryAttributeOrder> s)
        {
            return s.Set(s.Target.CategoryId, s.Source.CategoryId).Set(s.Target.AttributeId, s.Source.AttributeId).Set(s.Target.Order, s.Source.Order);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateKeyMapping(IDataMapSetter<TblCategoryAttribute, SgCategoryAttributeOrder> s)
        {
            return s.Set(s.Target.CategoryId, s.Source.CategoryId).Set(s.Target.AttributeId, s.Source.AttributeId);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateMapping(IDataMapSetter<TblCategoryAttribute, SgCategoryAttributeOrder> s)
        {
            return s.Set(s.Target.Order, s.Source.Order);
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<SgCategoryAttributeOrder, TblCategoryAttribute> GetReader()
        {
            return SgCategoryAttributeOrderReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgCategoryAttributeOrderReader : ISqModelReader<SgCategoryAttributeOrder, TblCategoryAttribute>
        {
            public static SgCategoryAttributeOrderReader Instance { get; } = new SgCategoryAttributeOrderReader();
            IReadOnlyList<ExprColumn> ISqModelReader<SgCategoryAttributeOrder, TblCategoryAttribute>.GetColumns(TblCategoryAttribute table)
            {
                return SgCategoryAttributeOrder.GetColumns(table);
            }

            SgCategoryAttributeOrder ISqModelReader<SgCategoryAttributeOrder, TblCategoryAttribute>.Read(ISqDataRecordReader record, TblCategoryAttribute table)
            {
                return SgCategoryAttributeOrder.Read(record, table);
            }

            SgCategoryAttributeOrder ISqModelReader<SgCategoryAttributeOrder, TblCategoryAttribute>.ReadOrdinal(ISqDataRecordReader record, TblCategoryAttribute table, int offset)
            {
                return SgCategoryAttributeOrder.ReadOrdinal(record, table, offset);
            }
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelUpdaterKey<SgCategoryAttributeOrder, TblCategoryAttribute> GetUpdater()
        {
            return SgCategoryAttributeOrderUpdater.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgCategoryAttributeOrderUpdater : ISqModelUpdaterKey<SgCategoryAttributeOrder, TblCategoryAttribute>
        {
            public static SgCategoryAttributeOrderUpdater Instance { get; } = new SgCategoryAttributeOrderUpdater();
            IRecordSetterNext ISqModelUpdater<SgCategoryAttributeOrder, TblCategoryAttribute>.GetMapping(IDataMapSetter<TblCategoryAttribute, SgCategoryAttributeOrder> dataMapSetter)
            {
                return SgCategoryAttributeOrder.GetMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<SgCategoryAttributeOrder, TblCategoryAttribute>.GetUpdateKeyMapping(IDataMapSetter<TblCategoryAttribute, SgCategoryAttributeOrder> dataMapSetter)
            {
                return SgCategoryAttributeOrder.GetUpdateKeyMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<SgCategoryAttributeOrder, TblCategoryAttribute>.GetUpdateMapping(IDataMapSetter<TblCategoryAttribute, SgCategoryAttributeOrder> dataMapSetter)
            {
                return SgCategoryAttributeOrder.GetUpdateMapping(dataMapSetter);
            }
        }

        private class SgCategoryAttributeReader : ISqModelReader<SgCategoryAttributeOrder, TblCategoryAttribute>
        {
            public static SgCategoryAttributeReader Instance { get; } = new SgCategoryAttributeReader();
            IReadOnlyList<ExprColumn> ISqModelReader<SgCategoryAttributeOrder, TblCategoryAttribute>.GetColumns(TblCategoryAttribute table)
            {
                return SgCategoryAttributeOrder.GetColumns(table);
            }

            SgCategoryAttributeOrder ISqModelReader<SgCategoryAttributeOrder, TblCategoryAttribute>.Read(ISqDataRecordReader record, TblCategoryAttribute table)
            {
                return SgCategoryAttributeOrder.Read(record, table);
            }

            SgCategoryAttributeOrder ISqModelReader<SgCategoryAttributeOrder, TblCategoryAttribute>.ReadOrdinal(ISqDataRecordReader record, TblCategoryAttribute table, int offset)
            {
                return SgCategoryAttributeOrder.ReadOrdinal(record, table, offset);
            }
        }

        private class SgCategoryAttributeUpdater : ISqModelUpdaterKey<SgCategoryAttributeOrder, TblCategoryAttribute>
        {
            public static SgCategoryAttributeUpdater Instance { get; } = new SgCategoryAttributeUpdater();
            IRecordSetterNext ISqModelUpdater<SgCategoryAttributeOrder, TblCategoryAttribute>.GetMapping(IDataMapSetter<TblCategoryAttribute, SgCategoryAttributeOrder> dataMapSetter)
            {
                return SgCategoryAttributeOrder.GetMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<SgCategoryAttributeOrder, TblCategoryAttribute>.GetUpdateKeyMapping(IDataMapSetter<TblCategoryAttribute, SgCategoryAttributeOrder> dataMapSetter)
            {
                return SgCategoryAttributeOrder.GetUpdateKeyMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<SgCategoryAttributeOrder, TblCategoryAttribute>.GetUpdateMapping(IDataMapSetter<TblCategoryAttribute, SgCategoryAttributeOrder> dataMapSetter)
            {
                return SgCategoryAttributeOrder.GetUpdateMapping(dataMapSetter);
            }
        }
    }
}