using System;
using SqExpress;
using SqGoods.DomainLogic.Views;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.QueryBuilders.RecordSetter;
using SqExpress.Syntax.Select.SelectItems;

namespace SqGoods.DomainLogic.Models
{
    public record SgCategoryAttNum
    {
        //Auto-generated by SqExpress Code-gen util
        public SgCategoryAttNum(Guid categoryId, int attributesCount)
        {
            this.CategoryId = categoryId;
            this.AttributesCount = attributesCount;
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgCategoryAttNum Read(ISqDataRecordReader record, VwCategoryAttNum table)
        {
            return new SgCategoryAttNum(categoryId: table.CategoryId.Read(record), attributesCount: table.AttributesCount.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgCategoryAttNum ReadWithPrefix(ISqDataRecordReader record, VwCategoryAttNum table, string prefix)
        {
            return new SgCategoryAttNum(categoryId: table.CategoryId.Read(record, prefix + table.CategoryId.ColumnName.Name), attributesCount: table.AttributesCount.Read(record, prefix + table.AttributesCount.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgCategoryAttNum ReadOrdinal(ISqDataRecordReader record, VwCategoryAttNum table, int offset)
        {
            return new SgCategoryAttNum(categoryId: table.CategoryId.Read(record, offset), attributesCount: table.AttributesCount.Read(record, offset + 1));
        }

        //Auto-generated by SqExpress Code-gen util
        public Guid CategoryId { get; }

        //Auto-generated by SqExpress Code-gen util
        public int AttributesCount { get; }

        //Auto-generated by SqExpress Code-gen util
        public static ExprColumn[] GetColumns(VwCategoryAttNum table)
        {
            return new ExprColumn[]{table.CategoryId, table.AttributesCount};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(VwCategoryAttNum table, string prefix)
        {
            return new ExprAliasedColumn[]{table.CategoryId.As(prefix + table.CategoryId.ColumnName.Name), table.AttributesCount.As(prefix + table.AttributesCount.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, VwCategoryAttNum table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, VwCategoryAttNum table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<SgCategoryAttNum, VwCategoryAttNum> GetReader()
        {
            return SgCategoryAttNumReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgCategoryAttNumReader : ISqModelReader<SgCategoryAttNum, VwCategoryAttNum>
        {
            public static SgCategoryAttNumReader Instance { get; } = new SgCategoryAttNumReader();
            IReadOnlyList<ExprColumn> ISqModelReader<SgCategoryAttNum, VwCategoryAttNum>.GetColumns(VwCategoryAttNum table)
            {
                return SgCategoryAttNum.GetColumns(table);
            }

            SgCategoryAttNum ISqModelReader<SgCategoryAttNum, VwCategoryAttNum>.Read(ISqDataRecordReader record, VwCategoryAttNum table)
            {
                return SgCategoryAttNum.Read(record, table);
            }

            SgCategoryAttNum ISqModelReader<SgCategoryAttNum, VwCategoryAttNum>.ReadOrdinal(ISqDataRecordReader record, VwCategoryAttNum table, int offset)
            {
                return SgCategoryAttNum.ReadOrdinal(record, table, offset);
            }
        }

        private class SgCategoryStatReader : ISqModelReader<SgCategoryAttNum, VwCategoryAttNum>
        {
            public static SgCategoryStatReader Instance { get; } = new SgCategoryStatReader();
            IReadOnlyList<ExprColumn> ISqModelReader<SgCategoryAttNum, VwCategoryAttNum>.GetColumns(VwCategoryAttNum table)
            {
                return SgCategoryAttNum.GetColumns(table);
            }

            SgCategoryAttNum ISqModelReader<SgCategoryAttNum, VwCategoryAttNum>.Read(ISqDataRecordReader record, VwCategoryAttNum table)
            {
                return SgCategoryAttNum.Read(record, table);
            }

            SgCategoryAttNum ISqModelReader<SgCategoryAttNum, VwCategoryAttNum>.ReadOrdinal(ISqDataRecordReader record, VwCategoryAttNum table, int offset)
            {
                return SgCategoryAttNum.ReadOrdinal(record, table, offset);
            }
        }
    }
}