using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqGoods.DomainLogic.Tables;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqGoods.DomainLogic.Models
{
    public record SgCategoryName
    {
        //Auto-generated by SqExpress Code-gen util
        public SgCategoryName(Guid id, string name)
        {
            this.Id = id;
            this.Name = name;
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgCategoryName Read(ISqDataRecordReader record, TblCategory table)
        {
            return new SgCategoryName(id: table.CategoryId.Read(record), name: table.Name.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgCategoryName ReadWithPrefix(ISqDataRecordReader record, TblCategory table, string prefix)
        {
            return new SgCategoryName(id: table.CategoryId.Read(record, prefix + table.CategoryId.ColumnName.Name), name: table.Name.Read(record, prefix + table.Name.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgCategoryName ReadOrdinal(ISqDataRecordReader record, TblCategory table, int offset)
        {
            return new SgCategoryName(id: table.CategoryId.Read(record, offset), name: table.Name.Read(record, offset + 1));
        }

        //Auto-generated by SqExpress Code-gen util
        public Guid Id { get; }

        //Auto-generated by SqExpress Code-gen util
        public string Name { get; }

        //Auto-generated by SqExpress Code-gen util
        public static TableColumn[] GetColumns(TblCategory table)
        {
            return new TableColumn[]{table.CategoryId, table.Name};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(TblCategory table, string prefix)
        {
            return new ExprAliasedColumn[]{table.CategoryId.As(prefix + table.CategoryId.ColumnName.Name), table.Name.As(prefix + table.Name.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, TblCategory table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, TblCategory table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetMapping(IDataMapSetter<TblCategory, SgCategoryName> s)
        {
            return s.Set(s.Target.CategoryId, s.Source.Id).Set(s.Target.Name, s.Source.Name);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateKeyMapping(IDataMapSetter<TblCategory, SgCategoryName> s)
        {
            return s.Set(s.Target.CategoryId, s.Source.Id);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateMapping(IDataMapSetter<TblCategory, SgCategoryName> s)
        {
            return s.Set(s.Target.Name, s.Source.Name);
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<SgCategoryName, TblCategory> GetReader()
        {
            return SgCategoryNameReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgCategoryNameReader : ISqModelReader<SgCategoryName, TblCategory>
        {
            public static SgCategoryNameReader Instance { get; } = new SgCategoryNameReader();
            IReadOnlyList<ExprColumn> ISqModelReader<SgCategoryName, TblCategory>.GetColumns(TblCategory table)
            {
                return SgCategoryName.GetColumns(table);
            }

            SgCategoryName ISqModelReader<SgCategoryName, TblCategory>.Read(ISqDataRecordReader record, TblCategory table)
            {
                return SgCategoryName.Read(record, table);
            }

            SgCategoryName ISqModelReader<SgCategoryName, TblCategory>.ReadOrdinal(ISqDataRecordReader record, TblCategory table, int offset)
            {
                return SgCategoryName.ReadOrdinal(record, table, offset);
            }
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelUpdaterKey<SgCategoryName, TblCategory> GetUpdater()
        {
            return SgCategoryNameUpdater.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgCategoryNameUpdater : ISqModelUpdaterKey<SgCategoryName, TblCategory>
        {
            public static SgCategoryNameUpdater Instance { get; } = new SgCategoryNameUpdater();
            IRecordSetterNext ISqModelUpdater<SgCategoryName, TblCategory>.GetMapping(IDataMapSetter<TblCategory, SgCategoryName> dataMapSetter)
            {
                return SgCategoryName.GetMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<SgCategoryName, TblCategory>.GetUpdateKeyMapping(IDataMapSetter<TblCategory, SgCategoryName> dataMapSetter)
            {
                return SgCategoryName.GetUpdateKeyMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<SgCategoryName, TblCategory>.GetUpdateMapping(IDataMapSetter<TblCategory, SgCategoryName> dataMapSetter)
            {
                return SgCategoryName.GetUpdateMapping(dataMapSetter);
            }
        }
    }
}