using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqGoods.DomainLogic.Views;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqGoods.DomainLogic.Models
{
    public record SgCategoryProductNum
    {
        //Auto-generated by SqExpress Code-gen util
        public SgCategoryProductNum(Guid categoryId, int productCount)
        {
            this.CategoryId = categoryId;
            this.ProductCount = productCount;
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgCategoryProductNum Read(ISqDataRecordReader record, VwCategoryProductNum table)
        {
            return new SgCategoryProductNum(categoryId: table.CategoryId.Read(record), productCount: table.ProductCount.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgCategoryProductNum ReadWithPrefix(ISqDataRecordReader record, VwCategoryProductNum table, string prefix)
        {
            return new SgCategoryProductNum(categoryId: table.CategoryId.Read(record, prefix + table.CategoryId.ColumnName.Name), productCount: table.ProductCount.Read(record, prefix + table.ProductCount.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgCategoryProductNum ReadOrdinal(ISqDataRecordReader record, VwCategoryProductNum table, int offset)
        {
            return new SgCategoryProductNum(categoryId: table.CategoryId.Read(record, offset), productCount: table.ProductCount.Read(record, offset + 1));
        }

        //Auto-generated by SqExpress Code-gen util
        public Guid CategoryId { get; }

        //Auto-generated by SqExpress Code-gen util
        public int ProductCount { get; }

        //Auto-generated by SqExpress Code-gen util
        public static ExprColumn[] GetColumns(VwCategoryProductNum table)
        {
            return new ExprColumn[]{table.CategoryId, table.ProductCount};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(VwCategoryProductNum table, string prefix)
        {
            return new ExprAliasedColumn[]{table.CategoryId.As(prefix + table.CategoryId.ColumnName.Name), table.ProductCount.As(prefix + table.ProductCount.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, VwCategoryProductNum table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, VwCategoryProductNum table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<SgCategoryProductNum, VwCategoryProductNum> GetReader()
        {
            return SgCategoryProductNumReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgCategoryProductNumReader : ISqModelReader<SgCategoryProductNum, VwCategoryProductNum>
        {
            public static SgCategoryProductNumReader Instance { get; } = new SgCategoryProductNumReader();
            IReadOnlyList<ExprColumn> ISqModelReader<SgCategoryProductNum, VwCategoryProductNum>.GetColumns(VwCategoryProductNum table)
            {
                return SgCategoryProductNum.GetColumns(table);
            }

            SgCategoryProductNum ISqModelReader<SgCategoryProductNum, VwCategoryProductNum>.Read(ISqDataRecordReader record, VwCategoryProductNum table)
            {
                return SgCategoryProductNum.Read(record, table);
            }

            SgCategoryProductNum ISqModelReader<SgCategoryProductNum, VwCategoryProductNum>.ReadOrdinal(ISqDataRecordReader record, VwCategoryProductNum table, int offset)
            {
                return SgCategoryProductNum.ReadOrdinal(record, table, offset);
            }
        }
    }
}