using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqGoods.DomainLogic.Tables;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqGoods.DomainLogic.Models
{
    public record SgCategory : ISgCategoryOrder, ISgCategoryIdentity
    {
        //Auto-generated by SqExpress Code-gen util
        public SgCategory(Guid id, string name, int order, int? topOrder)
        {
            this.Id = id;
            this.Name = name;
            this.Order = order;
            this.TopOrder = topOrder;
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgCategory Read(ISqDataRecordReader record, TblCategory table)
        {
            return new SgCategory(id: table.CategoryId.Read(record), name: table.Name.Read(record), order: table.Order.Read(record), topOrder: table.TopOrder.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgCategory ReadWithPrefix(ISqDataRecordReader record, TblCategory table, string prefix)
        {
            return new SgCategory(id: table.CategoryId.Read(record, prefix + table.CategoryId.ColumnName.Name), name: table.Name.Read(record, prefix + table.Name.ColumnName.Name), order: table.Order.Read(record, prefix + table.Order.ColumnName.Name), topOrder: table.TopOrder.Read(record, prefix + table.TopOrder.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgCategory ReadOrdinal(ISqDataRecordReader record, TblCategory table, int offset)
        {
            return new SgCategory(id: table.CategoryId.Read(record, offset), name: table.Name.Read(record, offset + 1), order: table.Order.Read(record, offset + 2), topOrder: table.TopOrder.Read(record, offset + 3));
        }

        //Auto-generated by SqExpress Code-gen util
        public Guid Id { get; }

        //Auto-generated by SqExpress Code-gen util
        public string Name { get; }

        //Auto-generated by SqExpress Code-gen util
        public int Order { get; }

        //Auto-generated by SqExpress Code-gen util
        public int? TopOrder { get; }

        //Auto-generated by SqExpress Code-gen util
        public static TableColumn[] GetColumns(TblCategory table)
        {
            return new TableColumn[]{table.CategoryId, table.Name, table.Order, table.TopOrder};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(TblCategory table, string prefix)
        {
            return new ExprAliasedColumn[]{table.CategoryId.As(prefix + table.CategoryId.ColumnName.Name), table.Name.As(prefix + table.Name.ColumnName.Name), table.Order.As(prefix + table.Order.ColumnName.Name), table.TopOrder.As(prefix + table.TopOrder.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, TblCategory table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, TblCategory table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetMapping(IDataMapSetter<TblCategory, SgCategory> s)
        {
            return s.Set(s.Target.CategoryId, s.Source.Id).Set(s.Target.Name, s.Source.Name).Set(s.Target.Order, s.Source.Order).Set(s.Target.TopOrder, s.Source.TopOrder);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateKeyMapping(IDataMapSetter<TblCategory, SgCategory> s)
        {
            return s.Set(s.Target.CategoryId, s.Source.Id);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateMapping(IDataMapSetter<TblCategory, SgCategory> s)
        {
            return s.Set(s.Target.Name, s.Source.Name).Set(s.Target.Order, s.Source.Order).Set(s.Target.TopOrder, s.Source.TopOrder);
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<SgCategory, TblCategory> GetReader()
        {
            return SgCategoryReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgCategoryReader : ISqModelReader<SgCategory, TblCategory>
        {
            public static SgCategoryReader Instance { get; } = new SgCategoryReader();
            IReadOnlyList<ExprColumn> ISqModelReader<SgCategory, TblCategory>.GetColumns(TblCategory table)
            {
                return SgCategory.GetColumns(table);
            }

            SgCategory ISqModelReader<SgCategory, TblCategory>.Read(ISqDataRecordReader record, TblCategory table)
            {
                return SgCategory.Read(record, table);
            }

            SgCategory ISqModelReader<SgCategory, TblCategory>.ReadOrdinal(ISqDataRecordReader record, TblCategory table, int offset)
            {
                return SgCategory.ReadOrdinal(record, table, offset);
            }
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelUpdaterKey<SgCategory, TblCategory> GetUpdater()
        {
            return SgCategoryUpdater.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgCategoryUpdater : ISqModelUpdaterKey<SgCategory, TblCategory>
        {
            public static SgCategoryUpdater Instance { get; } = new SgCategoryUpdater();
            IRecordSetterNext ISqModelUpdater<SgCategory, TblCategory>.GetMapping(IDataMapSetter<TblCategory, SgCategory> dataMapSetter)
            {
                return SgCategory.GetMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<SgCategory, TblCategory>.GetUpdateKeyMapping(IDataMapSetter<TblCategory, SgCategory> dataMapSetter)
            {
                return SgCategory.GetUpdateKeyMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<SgCategory, TblCategory>.GetUpdateMapping(IDataMapSetter<TblCategory, SgCategory> dataMapSetter)
            {
                return SgCategory.GetUpdateMapping(dataMapSetter);
            }
        }
    }
}