using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqGoods.DomainLogic.Tables;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqGoods.DomainLogic.Models
{
    public record SgProductAttributeSet
    {
        //Auto-generated by SqExpress Code-gen util
        public SgProductAttributeSet(Guid productId, Guid attributeSetId)
        {
            this.ProductId = productId;
            this.AttributeSetId = attributeSetId;
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgProductAttributeSet Read(ISqDataRecordReader record, TblProductAttributeSet table)
        {
            return new SgProductAttributeSet(productId: table.ProductId.Read(record), attributeSetId: table.AttributeSetId.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgProductAttributeSet ReadWithPrefix(ISqDataRecordReader record, TblProductAttributeSet table, string prefix)
        {
            return new SgProductAttributeSet(productId: table.ProductId.Read(record, prefix + table.ProductId.ColumnName.Name), attributeSetId: table.AttributeSetId.Read(record, prefix + table.AttributeSetId.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static SgProductAttributeSet ReadOrdinal(ISqDataRecordReader record, TblProductAttributeSet table, int offset)
        {
            return new SgProductAttributeSet(productId: table.ProductId.Read(record, offset), attributeSetId: table.AttributeSetId.Read(record, offset + 1));
        }

        //Auto-generated by SqExpress Code-gen util
        public Guid ProductId { get; }

        //Auto-generated by SqExpress Code-gen util
        public Guid AttributeSetId { get; }

        //Auto-generated by SqExpress Code-gen util
        public static TableColumn[] GetColumns(TblProductAttributeSet table)
        {
            return new TableColumn[]{table.ProductId, table.AttributeSetId};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(TblProductAttributeSet table, string prefix)
        {
            return new ExprAliasedColumn[]{table.ProductId.As(prefix + table.ProductId.ColumnName.Name), table.AttributeSetId.As(prefix + table.AttributeSetId.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, TblProductAttributeSet table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, TblProductAttributeSet table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetMapping(IDataMapSetter<TblProductAttributeSet, SgProductAttributeSet> s)
        {
            return s.Set(s.Target.ProductId, s.Source.ProductId).Set(s.Target.AttributeSetId, s.Source.AttributeSetId);
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<SgProductAttributeSet, TblProductAttributeSet> GetReader()
        {
            return SgProductAttributeSetReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgProductAttributeSetReader : ISqModelReader<SgProductAttributeSet, TblProductAttributeSet>
        {
            public static SgProductAttributeSetReader Instance { get; } = new SgProductAttributeSetReader();
            IReadOnlyList<ExprColumn> ISqModelReader<SgProductAttributeSet, TblProductAttributeSet>.GetColumns(TblProductAttributeSet table)
            {
                return SgProductAttributeSet.GetColumns(table);
            }

            SgProductAttributeSet ISqModelReader<SgProductAttributeSet, TblProductAttributeSet>.Read(ISqDataRecordReader record, TblProductAttributeSet table)
            {
                return SgProductAttributeSet.Read(record, table);
            }

            SgProductAttributeSet ISqModelReader<SgProductAttributeSet, TblProductAttributeSet>.ReadOrdinal(ISqDataRecordReader record, TblProductAttributeSet table, int offset)
            {
                return SgProductAttributeSet.ReadOrdinal(record, table, offset);
            }
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelUpdater<SgProductAttributeSet, TblProductAttributeSet> GetUpdater()
        {
            return SgProductAttributeSetUpdater.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class SgProductAttributeSetUpdater : ISqModelUpdater<SgProductAttributeSet, TblProductAttributeSet>
        {
            public static SgProductAttributeSetUpdater Instance { get; } = new SgProductAttributeSetUpdater();
            IRecordSetterNext ISqModelUpdater<SgProductAttributeSet, TblProductAttributeSet>.GetMapping(IDataMapSetter<TblProductAttributeSet, SgProductAttributeSet> dataMapSetter)
            {
                return SgProductAttributeSet.GetMapping(dataMapSetter);
            }
        }
    }
}